master:
  image: "registry.cn-hangzhou.aliyuncs.com/ringtail/jessie-sshd:v1.0"
  environment:
    - AUTHORIZED_KEYS: "${your public key}"
    - DISABLE_HOST_CHECK: true
  volumes:
    - ${your private key path}:/root/.ssh/id_rsa
  links:
    - "slave1:slave1"
slave1:
  image: "registry.cn-hangzhou.aliyuncs.com/ringtail/jessie-sshd:v1.0"
  environment:
    - AUTHORIZED_KEYS:"${your public key}"
